# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v3
    - name: Install GSL on macOS
      if: matrix.runner == 'macos-latest'
      run: |
        brew update
        brew install gsl
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Run tests
      run: uv run --group test --no-extra gpu --exact py.test -xvs
  test-gpu:
    runs-on: [self-hosted, linux, X64, gpu]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Run tests
      run: uv run --group test --extra gpu --exact py.test -xvs
